config/routes.rb
Rails.application.routes.draw do
  resources :shipments
  resources :accounts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shipment.rb
class Shipment < ApplicationRecord
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy!

    respond_to do |format|
      format.html { redirect_to accounts_path, status: :see_other, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:balance)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_action :set_shipment, only: %i[ show edit update destroy ]

  # GET /shipments or /shipments.json
  def index
    @shipments = Shipment.all
  end

  # GET /shipments/1 or /shipments/1.json
  def show
  end

  # GET /shipments/new
  def new
    @shipment = Shipment.new
  end

  # GET /shipments/1/edit
  def edit
  end

  # POST /shipments or /shipments.json
  def create
    @shipment = Shipment.new(shipment_params)

    respond_to do |format|
      if @shipment.save
        format.html { redirect_to @shipment, notice: "Shipment was successfully created." }
        format.json { render :show, status: :created, location: @shipment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shipments/1 or /shipments/1.json
  def update
    respond_to do |format|
      if @shipment.update(shipment_params)
        format.html { redirect_to @shipment, notice: "Shipment was successfully updated." }
        format.json { render :show, status: :ok, location: @shipment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipments/1 or /shipments/1.json
  def destroy
    @shipment.destroy!

    respond_to do |format|
      format.html { redirect_to shipments_path, status: :see_other, notice: "Shipment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipment
      @shipment = Shipment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shipment_params
      params.require(:shipment).permit(:pkg_no)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <p>
    <strong>Balance:</strong>
    <%= account.balance %>
  </p>

</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :balance, style: "display: block" %>
    <%= form.number_field :balance %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<% content_for :title, "Editing account" %>

<h1>Editing account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Show this account", @account %> |
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Accounts" %>

<h1>Accounts</h1>

<div id="accounts">
  <% @accounts.each do |account| %>
    <%= render account %>
    <p>
      <%= link_to "Show this account", account %>
    </p>
  <% end %>
</div>

<%= link_to "New account", new_account_path %>

app/views/accounts/new.html.erb
<% content_for :title, "New account" %>

<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @account %>

<div>
  <%= link_to "Edit this account", edit_account_path(@account) %> |
  <%= link_to "Back to accounts", accounts_path %>

  <%= button_to "Destroy this account", @account, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Shipmondo A" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shipments/_form.html.erb
<%= form_with(model: shipment) do |form| %>
  <% if shipment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shipment.errors.count, "error") %> prohibited this shipment from being saved:</h2>

      <ul>
        <% shipment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :pkg_no, style: "display: block" %>
    <%= form.text_field :pkg_no %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shipments/_shipment.html.erb
<div id="<%= dom_id shipment %>">
  <p>
    <strong>Pkg no:</strong>
    <%= shipment.pkg_no %>
  </p>

</div>

app/views/shipments/edit.html.erb
<% content_for :title, "Editing shipment" %>

<h1>Editing shipment</h1>

<%= render "form", shipment: @shipment %>

<br>

<div>
  <%= link_to "Show this shipment", @shipment %> |
  <%= link_to "Back to shipments", shipments_path %>
</div>

app/views/shipments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Shipments" %>

<h1>Shipments</h1>

<div id="shipments">
  <% @shipments.each do |shipment| %>
    <%= render shipment %>
    <p>
      <%= link_to "Show this shipment", shipment %>
    </p>
  <% end %>
</div>

<%= link_to "New shipment", new_shipment_path %>

app/views/shipments/new.html.erb
<% content_for :title, "New shipment" %>

<h1>New shipment</h1>

<%= render "form", shipment: @shipment %>

<br>

<div>
  <%= link_to "Back to shipments", shipments_path %>
</div>

app/views/shipments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shipment %>

<div>
  <%= link_to "Edit this shipment", edit_shipment_path(@shipment) %> |
  <%= link_to "Back to shipments", shipments_path %>

  <%= button_to "Destroy this shipment", @shipment, method: :delete %>
</div>